server:
  port: 8081
      
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health    
   
zuul:
  ignoredServices: '*'
  routes:
    user-proxy: /user-api/**
    product-proxy: /product-api/**
    auth-server:
      path: /uaa/**
      stripPrefix: false
  ConnectTimeout: 30000  
  ReadTimeout: 30000
