server:
  port: 8081
      
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /routes
    healthCheckUrlPath: /health    
   
zuul:
  ignoredServices: '*'
  routes:
    user-proxy: /user-api/**
    product-proxy: /product-api/**
    auth-server:
      sensitiveHeaders:
      path: /auth/**
      stripPrefix: false
          
security:  
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://192.168.99.1:8081/auth/oauth/token
      userAuthorizationUri: http://192.168.99.1:8081/auth/oauth/authorize      
      clientId: acme
      clientSecret: acmesecret
      grantType: authorization_code
    resource:
      userInfoUri: http://192.168.99.1:8081/auth/user

      
logging:
  level.org.springframework.security: DEBUG
